# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/util/event.proto

require 'google/protobuf'

require 'tensorflow/core/framework/summary_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tensorflow/core/util/event.proto", :syntax => :proto3) do
    add_message "tensorflow.Event" do
      optional :wall_time, :double, 1
      optional :step, :int64, 2
      oneof :what do
        optional :file_version, :string, 3
        optional :graph_def, :bytes, 4
        optional :summary, :message, 5, "tensorflow.Summary"
        optional :log_message, :message, 6, "tensorflow.LogMessage"
        optional :session_log, :message, 7, "tensorflow.SessionLog"
        optional :tagged_run_metadata, :message, 8, "tensorflow.TaggedRunMetadata"
        optional :meta_graph_def, :bytes, 9
      end
    end
    add_message "tensorflow.LogMessage" do
      optional :level, :enum, 1, "tensorflow.LogMessage.Level"
      optional :message, :string, 2
    end
    add_enum "tensorflow.LogMessage.Level" do
      value :UNKNOWN, 0
      value :DEBUGGING, 10
      value :INFO, 20
      value :WARN, 30
      value :ERROR, 40
      value :FATAL, 50
    end
    add_message "tensorflow.SessionLog" do
      optional :status, :enum, 1, "tensorflow.SessionLog.SessionStatus"
      optional :checkpoint_path, :string, 2
      optional :msg, :string, 3
    end
    add_enum "tensorflow.SessionLog.SessionStatus" do
      value :STATUS_UNSPECIFIED, 0
      value :START, 1
      value :STOP, 2
      value :CHECKPOINT, 3
    end
    add_message "tensorflow.TaggedRunMetadata" do
      optional :tag, :string, 1
      optional :run_metadata, :bytes, 2
    end
    add_message "tensorflow.WatchdogConfig" do
      optional :timeout_ms, :int64, 1
    end
    add_message "tensorflow.RequestedExitCode" do
      optional :exit_code, :int32, 1
    end
    add_message "tensorflow.WorkerHeartbeatRequest" do
      optional :shutdown_mode, :enum, 1, "tensorflow.WorkerShutdownMode"
      optional :watchdog_config, :message, 2, "tensorflow.WatchdogConfig"
      optional :exit_code, :message, 3, "tensorflow.RequestedExitCode"
    end
    add_message "tensorflow.WorkerHeartbeatResponse" do
      optional :health_status, :enum, 1, "tensorflow.WorkerHealth"
      repeated :worker_log, :message, 2, "tensorflow.Event"
      optional :hostname, :string, 3
    end
    add_enum "tensorflow.WorkerHealth" do
      value :OK, 0
      value :RECEIVED_SHUTDOWN_SIGNAL, 1
      value :INTERNAL_ERROR, 2
      value :SHUTTING_DOWN, 3
    end
    add_enum "tensorflow.WorkerShutdownMode" do
      value :DEFAULT, 0
      value :NOT_CONFIGURED, 1
      value :WAIT_FOR_COORDINATOR, 2
      value :SHUTDOWN_AFTER_TIMEOUT, 3
    end
  end
end

module Tensorflow
  Event = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.Event").msgclass
  LogMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.LogMessage").msgclass
  LogMessage::Level = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.LogMessage.Level").enummodule
  SessionLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.SessionLog").msgclass
  SessionLog::SessionStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.SessionLog.SessionStatus").enummodule
  TaggedRunMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.TaggedRunMetadata").msgclass
  WatchdogConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.WatchdogConfig").msgclass
  RequestedExitCode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.RequestedExitCode").msgclass
  WorkerHeartbeatRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.WorkerHeartbeatRequest").msgclass
  WorkerHeartbeatResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.WorkerHeartbeatResponse").msgclass
  WorkerHealth = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.WorkerHealth").enummodule
  WorkerShutdownMode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.WorkerShutdownMode").enummodule
end
